import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Playlist | Music",
    description: "Generated by create next app",
};

export default function PlaylistLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return <>{children}</>;
}
